name: Export Flox Environment and Upload to Azure

on:
  workflow_dispatch:
    inputs:
      library_name:
        description: "Library name to install"
        required: true
      version:
        description: "Library version (optional)"
        required: false
      azure_storage_name:
        description: "Azure Storage Account Name"
        required: true
      azure_storage_file_share:
        description: "Azure Storage File Share Name"
        required: true
      storage_key:
        description: "Azure Storage Account Key"
        required: false
        type: secret

jobs:
  export-and-upload:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_KEY: ${{ secrets.storage_key }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Azure Linux Mariner image
        run: |
          docker pull mcr.microsoft.com/cbl-mariner/base/core:2.0

      - name: Run Flox export in container
        run: |
          LIBRARY="${{ github.event.inputs.library_name }}"
          VERSION="${{ github.event.inputs.version }}"
          STORAGE_ACCOUNT="${{ github.event.inputs.azure_storage_name }}"
          STORAGE_FILE_SHARE="${{ github.event.inputs.azure_storage_file_share }}"
          STORAGE_KEY="${{ secrets.storage_key }}"
          ENV_NAME="ci-flox-env"

          if [ -z "$VERSION" ]; then
            INSTALL_CMD="flox install $LIBRARY"
          else
            INSTALL_CMD="flox install $LIBRARY@$VERSION"
          fi

          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -e AZURE_STORAGE_KEY="$STORAGE_KEY" \
            mcr.microsoft.com/cbl-mariner/base/core:2.0 \
            bash -c "
              tdnf install -y ca-certificates
              tdnf install -y util-linux which git wget bash coreutils which sudo tar gzip
              chmod +x /workspace/chroot-flox-install.sh
              /workspace/chroot-flox-install.sh
              chown -R nixuser:nixuser /home/nixuser
              # Create flox environment and install library
                su - nixuser <<EOF
                        mkdir /home/nixuser/$ENV_NAME && cd /home/nixuser/$ENV_NAME
                        flox init
                        $INSTALL_CMD
                EOF
              # Export environment
              /workspace/export_env.sh /home/nixuser/$ENV_NAME
              # Upload to Azure Storage
              /workspace/upload_to_azure_storage.sh /home/nixuser/$ENV_NAME/export $STORAGE_ACCOUNT $STORAGE_KEY $STORAGE_FILE_SHARE
            "
